// -----------------------------------------------------------------------------
//  fw_build_info.h — build fingerprint reported in the identify banner.
//
//  AUTO-GENERATED by octacam's firmware provisioning (octacam/firmware.py) at
//  flash time; the value committed here is a PLACEHOLDER. See the identical
//  header in arduino/triggerbox/ for the full rationale: octacam recomputes a
//  short hash of the sketch source, bakes it into a throwaway copy at flash time
//  (never dirtying the repo), and compares it against the "2PHOTON <ver> <build>"
//  identify reply to tell whether the exact current firmware is on the board.
// -----------------------------------------------------------------------------
#pragma once
#define TWOPHOTON_FW_BUILD "UNBAKED"
