// -----------------------------------------------------------------------------
//  fw_build_info.h — build fingerprint reported in the identify banner.
//
//  AUTO-GENERATED by octacam's firmware provisioning (octacam/firmware.py) at
//  flash time. octacam recomputes a short hash of the sketch source and bakes it
//  in here just before it compiles+uploads, then compares the value the board
//  reports (`TRIGGERBOX <ver> <build>`) against the source on disk — so it can
//  tell whether the *exact* current firmware is running and offer to reflash if
//  not.
//
//  The value committed here is a PLACEHOLDER. octacam writes the real hash into a
//  throwaway copy of the sketch, so the repo tree is never dirtied by a flash. A
//  board flashed by hand (`arduino-cli compile --upload arduino/triggerbox`)
//  reports this placeholder, which octacam will (correctly) see as "not the
//  managed build" and offer to reflash. The define must always be present so the
//  sketch compiles standalone.
// -----------------------------------------------------------------------------
#pragma once
#define TRIGGERBOX_FW_BUILD "UNBAKED"
